### ISSUE TITLE
Precision loss?

### ISSUE THREAD

**Issue by mborowczak** [UW-COSC-2030-FA-2017/lab1-processlist-GoAndBeeCool#2]
Looks like you're assuming that the file contains just integers.

`int i;`
...
` file >> i  `
...
`cout <<  i`

Maybe consider changing the type of `i` to a `double`?

**Comment by GoAndBeeCool** [comment]
Thanks, I'll commit the change now.

**Comment by mborowczak** [comment]
Awesome - nice going. 

So - cool feature when using github, if you include one of several keywords (see below) and the Issue number - when you push your commit back to github it automatically closes the open issue.

- close
- closes
- closed
- fix
- fixes
- fixed
- resolve
- resolves
- resolved

E.g in this case the commit message could have been: "Fixes #2 by changing i to a float."

**Comment by GoAndBeeCool** [comment]
Alright I just tested it out, apparently this is issue #2 because I accidentally used the "Fixed" keyword in one of my previous commits.
